apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: azure-ai-back
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: azure-ai-back
    spec:
      containers:
      - name: azure-ai-back
        image: arcName.azurecr.io/model-img:v1
        ports:
        - containerPort: 80 
          name: model-img
---
apiVersion: v1
kind: Service
metadata:
  name: azure-ai-back
spec:
  ports:
  - port: 80
  selector:
    app: azure-ai-back
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: azure-ai-front
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5 
  template:
    metadata:
      labels:
        app: azure-ai-front
    spec:
      containers:
      - name: azure-ai-front
        image: arcName.azurecr.io/app-img:v1 
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 250m
          limits:
            cpu: 500m
        env:
        - name: mymodel
          value: "azure-ai-back"
---
apiVersion: v1
kind: Service
metadata:
  name: azure-ai-front
spec:
  type: LoadBalancer
  ports:
  - port: 8080
  selector:
    app: azure-ai-front
